# Generated by Django 6.0.7 on 2026-08-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_student_alter_class_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='temp', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='temp2', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
