# Generated by Django 6.0.7 on 2026-08-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_student_password_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, to='testApp.class'),
        ),
    ]
