# Generated by Django 6.0.7 on 2026-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_class_student_class_code_class_section'),
        ('testApp', '0004_student_classes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, to='classes.class'),
        ),
    ]
